repos:
  - repo: local
    hooks:
      - id: poetry-export
        name: Export requirements.txt from Poetry
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: system
        files: ^(pyproject\.toml|poetry\.lock)$
        pass_filenames: false
